/**
 * Bridge: TypeScript content-component schemas → JSON consumable by the
 * `stripe.markdoc-language-support` VS Code extension.
 *
 * Why this exists
 * ---------------
 * The extension's language server reads a `markdoc.config.json` at the
 * workspace root, which in turn points at an ESM/CJS JavaScript module that
 * default-exports Markdoc's runtime config (`{ tags, nodes?, functions? }`).
 * It does NOT load `.ts` source directly, so feeding it our
 * `markdoc.config.ts` — which imports Astro's `component()` helper and each
 * component's `schema.ts` — won't work.
 *
 * This script takes the raw `markdoc` shape from each content-component's
 * `schema.ts` (no Astro helpers, no keystatic state), strips `render` (a
 * runtime concern the language server doesn't need — it only wants attribute
 * names/types/required flags for completion and validation), and emits a
 * self-contained ESM module at `.markdoc/schema.generated.mjs`. The committed
 * `markdoc.config.json` points at that file.
 *
 * Run modes
 * ---------
 *   sync-markdoc-config.ts            — regenerate and write. Idempotent.
 *   sync-markdoc-config.ts --check    — regenerate in-memory, diff against
 *                                        files on disk, exit 1 if drift.
 *                                        Used by CI via `npm run validate`.
 *
 * Runs on `predev` so local editors always see fresh config.
 */
import fs from "node:fs";
import path from "node:path";
import { components } from "../src/content-components/index.ts";
import type { Schema, SchemaAttribute } from "@markdoc/markdoc";

const ROOT = path.resolve(import.meta.dirname, "..");
const SCHEMA_OUT = path.join(ROOT, ".markdoc/schema.generated.mjs");
const CONFIG_OUT = path.join(ROOT, "markdoc.config.json");

const hasCheckFlag = process.argv.includes("--check");

// ---------------------------------------------------------------------------
// Serialization
// ---------------------------------------------------------------------------

/**
 * Render one of Markdoc's `SchemaAttribute` type-constructor references as a
 * JS identifier literal. Markdoc accepts the primitive constructors (String /
 * Number / Boolean / Array / Object) plus custom classes; we only emit the
 * primitives since that's all our schemas use. Anything else falls back to
 * `String` with a warning so the extension still has something to chew on.
 */
function serializeAttributeType(type: SchemaAttribute["type"]): string {
  if (type === String) return "String";
  if (type === Number) return "Number";
  if (type === Boolean) return "Boolean";
  if (type === Array) return "Array";
  if (type === Object) return "Object";
  // Custom validator class or unknown — the language server only cares for
  // completion, so degrading to String is safer than crashing.
  return "String";
}

/**
 * Strip `render` (not needed by the language server) and emit each attribute
 * as a JS object literal with the type constructor rendered as a bareword
 * reference to the global.
 */
function serializeTag(tag: Schema, tagName: string): string {
  const hasAttrs = tag.attributes && Object.keys(tag.attributes).length > 0;
  if (!tag.selfClosing && !hasAttrs) {
    // No meaningful config — tag name is all the language server needs.
    return `    "${tagName}": {},`;
  }
  const lines: string[] = [`    "${tagName}": {`];
  if (tag.selfClosing) lines.push(`      selfClosing: true,`);
  if (hasAttrs) {
    lines.push(`      attributes: {`);
    for (const [attrName, attr] of Object.entries(tag.attributes!)) {
      const parts: string[] = [`type: ${serializeAttributeType(attr.type)}`];
      if (attr.required) parts.push(`required: true`);
      if (attr.default !== undefined) parts.push(`default: ${JSON.stringify(attr.default)}`);
      if (attr.matches !== undefined) parts.push(`matches: ${JSON.stringify(attr.matches)}`);
      lines.push(`        "${attrName}": { ${parts.join(", ")} },`);
    }
    lines.push(`      },`);
  }
  lines.push(`    },`);
  return lines.join("\n");
}

function buildSchemaModuleSource(): string {
  const tagLines = components
    .map(({ tagName, markdoc }) => serializeTag(markdoc, tagName))
    .join("\n");
  return `// AUTO-GENERATED by scripts/sync-markdoc-config.ts — DO NOT EDIT.
// Source: src/content-components/*/schema.ts (the \`markdoc\` export).
// Consumed by stripe.markdoc-language-support via markdoc.config.json.
// Regenerate with: npm run sync:markdoc-config

export default {
  tags: {
${tagLines}
  },
};
`;
}

function buildConfigJson(): string {
  // Extension expects a top-level array of server configs. We only have one.
  // `schema.path` is relative to workspace root; `type: "esm"` + omitted
  // `property` means the language server uses the module's default export.
  const config = [
    {
      id: "musician-site",
      path: "src/content/pages",
      schema: {
        path: ".markdoc/schema.generated.mjs",
        type: "esm",
        watch: true,
      },
      routing: {
        frontmatter: "route",
      },
    },
  ];
  return JSON.stringify(config, null, 2) + "\n";
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const schemaSource = buildSchemaModuleSource();
const configSource = buildConfigJson();

if (hasCheckFlag) {
  const schemaOnDisk = fs.existsSync(SCHEMA_OUT)
    ? fs.readFileSync(SCHEMA_OUT, "utf-8")
    : "";
  const configOnDisk = fs.existsSync(CONFIG_OUT)
    ? fs.readFileSync(CONFIG_OUT, "utf-8")
    : "";

  const schemaDrifted = schemaOnDisk !== schemaSource;
  const configDrifted = configOnDisk !== configSource;

  if (schemaDrifted || configDrifted) {
    console.error("Markdoc config is out of sync with src/content-components/.\n");
    if (schemaDrifted) {
      console.error(`  ✗ ${path.relative(ROOT, SCHEMA_OUT)} differs from the generated source`);
    }
    if (configDrifted) {
      console.error(`  ✗ ${path.relative(ROOT, CONFIG_OUT)} differs from the generated source`);
    }
    console.error("\nRun `npm run sync:markdoc-config` and commit the changes.");
    process.exit(1);
  }

  // Silent on success — keeps CI output uncluttered. Exit 0 implicitly.
} else {
  fs.mkdirSync(path.dirname(SCHEMA_OUT), { recursive: true });
  fs.writeFileSync(SCHEMA_OUT, schemaSource);
  fs.writeFileSync(CONFIG_OUT, configSource);

  // One-line log so predev output stays quiet. Uses relative paths for
  // readability.
  const tagCount = components.length;
  console.log(
    `markdoc-config: wrote ${tagCount} tags → ${path.relative(ROOT, CONFIG_OUT)} + ${path.relative(ROOT, SCHEMA_OUT)}`,
  );
}

